### ISSUE TITLE
Korean is broken in PDF 

### ISSUE THREAD

**Issue by soimkim** [fosslight/fosslight#1005]
**Describe the bug**
Korean is broken in PDF.
![image](https://github.com/fosslight/fosslight/assets/4284712/46e2e56e-1660-41ef-9eea-7583591187c9)

**Comment by soimkim** [comment]
@MyunghyunNero , 해당 버그 F/U해주시겠어요?

**Comment by MyunghyunNero** [comment]
@soimkim  넵 알겠습니다!
