### ISSUE TITLE
Some images not working

### ISSUE THREAD

**Issue by jongwooo** [fosslight/fosslight#1026]
**Describe the bug**

> sh: 1: ./wait-for: Permission denied

The project's [image](https://hub.docker.com/layers/fosslight/fosslight/latest/images/sha256-19a0390e92568d5725f05d599c2ca220ddb080eb28491d3c00a246c1c5e87ab7?context=explore) throws the above error and terminates.

**To Reproduce**

In the `docker-compose.yml` file, replace `build: .` with `image: fosslight/fosslight:latest` (or `v1.6.1`, `v1.6.2`).

```bash
docker-compose up
```

**System Environment (please complete the following information):**

 - Version: [v1.6.1](https://hub.docker.com/layers/fosslight/fosslight/v1.6.1/images/sha256-e5c8e4cc3f0583af2a0a11c0e828e748837256428af6f63c932a558644f90400?context=explore), [v1.6.2](https://hub.docker.com/layers/fosslight/fosslight/v1.6.2/images/sha256-19a0390e92568d5725f05d599c2ca220ddb080eb28491d3c00a246c1c5e87ab7?context=explore), [latest](https://hub.docker.com/layers/fosslight/fosslight/latest/images/sha256-19a0390e92568d5725f05d599c2ca220ddb080eb28491d3c00a246c1c5e87ab7?context=explore)

**Additional context**

None

**Comment by jongwooo** [comment]
[v1.4.11](https://hub.docker.com/layers/fosslight/fosslight/v1.4.11/images/sha256-72ad66179d3e677353027e2cd06f5f7014639a3ee907260891baccd74a04c925?context=explore) works fine.

**Comment by hyeinlee00** [comment]
@jongwooo Could you follow up this issue? :)

**Comment by jongwooo** [comment]
@hyeinlee00 Sure thing:)

**Comment by hyeinlee00** [comment]
@jongwooo  thank you! 👍

**Comment by jongwooo** [comment]
@hyeinlee00 How about reverting #996? I've been facing this issue since we started using the jib, so I'd suggest reverting first, fixing the broken image, and then applying the jib again. WDYT?

**Comment by hyeinlee00** [comment]
@jongwooo sorry for late answer.
I also agree that fixing the broken image should be the first step.
Please proceed with this issue as you said. Thank you.
