### ISSUE TITLE
When I Export(Spreadsheet) and check, there is no data.

### ISSUE THREAD

**Issue by dongs0** [fosslight/fosslight#1030]
**Describe the bug**
Identification에서 SRC or BIN 탭에서 Export(Spreadsheet)를 수행하면 빈데이터로 출력이 됨. (YAML은 정상적으로 데이터 출력)

**To Reproduce**
Project List > SRC or BIN > Export >  FOSSLight Report (Spreadsheet)

**Expected behavior**
출력결과에 BOM 정보 추가

**System Environment (please complete the following information):**
 - chrome
 - Our hub is FOSSLight Hub 1.6.1 but demo.fosslight is same situration

**Comment by hyeinlee00** [comment]
[#1033](https://github.com/fosslight/fosslight/issues/1033) 와 동일한 이슈입니다.

이슈 수정 후 업데이트 하겠습니다.

**Comment by Min-Kyungsun** [comment]
@dongs0 님
대응이 많이 지연된점 양해 부탁드리겠습니다.
사용에 불편함을 드려서 죄송합니다.
이슈 수정이 되어 v1.6.4 branch에 반영 완료 하였습니다.
해당 branch로 정상적으로 동작하는 것을 확인 하실 수 있습니다.
