### ISSUE TITLE
The list lncluded when exporting the Project List is strange

### ISSUE THREAD

**Issue by dongs0** [fosslight/fosslight#1032]
**Describe the bug**
The Project List displayed and the actual exported list are different.

**To Reproduce**
Issue 1. Project List > Export
Issue 2. Project List > selected checkbox that some project > Export
Issue 3. Project List > Search anything > Export

**Expected behavior**
Issue 1. 현재 Project List view에 보이는 프로젝트들 전체 출력
Issue 2. 체크 박스를 통해 선택한 Project LIst들을 출력
Issue 3. Project Name 검색했을 떄 나오는 Project List들을 출력

**System Environment (please complete the following information):**
 - chrome
 - demo fosslight에서도 동일한 증상

**Comment by hyeinlee00** [comment]
Project List에서 Export했을 때 3번과 같은 동작이 본래 의도 되었던 동작입니다.

Issue1, Issue3 은 현재 정상동작 하지 않는 것을 확인하였습니다.
Issue2의 경우 enhancement로 추가되어야하는 기능입니다.

우선 issue1, issue3 에 대해 파악한 후 업데이트 된 내용이 있으면 comment남기겠습니다.

**Comment by hyeinlee00** [comment]
이전에 동일한 이슈가 있어 수정한 적이 있는데, 변경 사항 반영이 안된 것 같습니다.
당시 이슈 원인은, 검색 기준에 watcher가 빈 값으로 설정된 것으로 보고 export되는 현상이 있었습니다.

**Comment by hyeinlee00** [comment]
[v1.6.3 ](https://github.com/fosslight/fosslight/releases/tag/v1.6.3) 업데이트를 통해 이슈 재현되지 않는 것을 확인하여 close합니다.
issue2에 작성해주신 동작은 기여해주신다면 대환영입니다 :)
