### ISSUE TITLE
Project List 메뉴에서 보여지는 Download내 FOSSLight Report를 Download하면 Identification에서 입력한 내용이 포함되지 않음

### ISSUE THREAD

**Issue by warmindifference** [fosslight/fosslight#1033]
**Describe the bug**
Open Source가 포함된 Project에서 FOSSLight Report를 Download하면 해당 프로젝트에 포함된 Open Source List 등의 정보는 보여지지 않음
FOSSLight Report의 Template만 Download 되는 것으로 보여짐
OSS Notice에는 Open Source List가 포함됨

**To Reproduce**
Admin으로 로그인
1. Project 생성 
2. 3rd Party, BIN : Not Applicable 선택/Save
3. SRC에 Open Source 포함/Save
4. BOM Merge & Save  / Request /Review Start/Confirm
5. Project List에서 해당 Project의 FOSSLight Report Download
6. SRC 및 BOM Tab 확인하면  Open Source 정보 없음
---
7. Package 에서 기본 정보를 그대로 두고 Save / Request / Review Start / Confirm 후 OSS Notice Download
8. OSS Notice 확인 (비교를 위한 TEST로 OSS Notive에서는 Open Source 정보 포함됨이 확인됨)

**Expected behavior**
6번에서 Open Source 정보가 포함되어 나타나기를 기대함

**Screenshots**
https://demo.fosslight.org/ 의 Project ID:648

**System Environment (please complete the following information):**
 - Browser [Chrome]
 - Version [Version 121.0.6167.161 (Official Build) (64-bit)]
 - Demo Site에서 Admin 계정 사용

**Additional context**
Local에 설치한 것도 결과 동일합니다.

**Comment by hyeinlee00** [comment]
증상 확인하였습니다. 남겨주신 것처럼 report 파일 양식만 다운로드 되는 것 같습니다.
수정되면 comment 업데이트 하겠습니다.

**Comment by Min-Kyungsun** [comment]
@warmindifference 님
대응이 많이 지연된점 양해 부탁드리겠습니다.
사용에 불편함을 드려서 죄송합니다.
이슈 수정이 되어 v1.6.4 branch에 반영 완료 하였습니다.
해당 branch로 정상적으로 동작하는 것을 확인 하실 수 있습니다.
