### ISSUE TITLE
NVD 취약점 리스트 가져올때 HTTP_NOT_FOUND 발생 하는 건 (resultsPerPage parameter cannot exceed 500)

### ISSUE THREAD

**Issue by mooli8342** [fosslight/fosslight#1040]
Describe the bug

To Reproduce

Expected behavior

Screenshots

System Environment (please complete the following information):

Etc
Additional context

v1.6.2 기준으로 

취약점 리스트를 새로 가져오기 위해, DB 초기화 후, schedule 을 돌렸는데 에러가 발생 했습니다.
로그를 디버깅 해보니, 기존에 List 2000개를 가져오는 부분이 에러가 발생 됩니다. 500개 이상의 resultsPerPage 를 가져 올 수 없다고 나오는데
소스코드는(/src/main/java/oss/fosslight/service/NvdDataService.java) 2000개 가져오게 되어 있더라구요.

[테스트주소]
https://services.nvd.nist.gov/rest/json/cpematch/2.0?resultsPerpage=500  -> 성공https://services.nvd.nist.gov/rest/json/cpematch/2.0?resultsPerpage=2000 -> 실패 (HTTP_404_NOT_FOUND)

이걸 수정해서 하면 될 거 같은데, 혹시 이거 외에 다른 코드를 수정해야 할게 있을까요?
아래 schedule.log 및 debug.log 기록 하였습니다. 

2024-04-17 18:00:07.854 1946581 [taskScheduler-1] INFO  [NvdDataService.java, nvdMetaDataApiJob():574] - nvdMetaDataApiJob start 
2024-04-17 18:00:07.905 1946632 [taskScheduler-1] INFO  [NvdDataService.java, nvdMetaDataApiJob():602] - nvdMetaMatch index : 0 / totalResults : 528910 
2024-04-17 18:00:08.579 1947306 [taskScheduler-1] ERROR [NvdDataService.java, getDataForRestApiConnection():889] - **httpsURLConnection error : HTTP_NOT_FOUND** 
2024-04-17 18:00:08.580 1947307 [taskScheduler-1] WARN  [NvdDataService.java, getDataForRestApiConnection():905] - Try again in 15 seconds... 
2024-04-17 18:00:24.212 1962939 [taskScheduler-1] ERROR [NvdDataService.java, getDataForRestApiConnection():889] - **httpsURLConnection error : HTTP_NOT_FOUND** 
2024-04-17 18:01:27.715 2026442 [taskScheduler-1] ERROR [NvdDataService.java, nvdMetaDataApiJob():701] - **url connection attempts exceeded** 

DEBUG 24-04-17 18:00:07[taskScheduler-1] [org.mybatis.spring.SqlSessionUtils:49] - Creating a new SqlSession 
DEBUG 24-04-17 18:00:07[taskScheduler-1] [org.mybatis.spring.SqlSessionUtils:49] - SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@3edc8472] was not registered for synchronization because synchronization is not active 
DEBUG 24-04-17 18:00:07[taskScheduler-1] [o.s.jdbc.datasource.DataSourceUtils:116] - Fetching JDBC Connection from DataSource 
DEBUG 24-04-17 18:00:07[taskScheduler-1] [o.m.s.t.SpringManagedTransaction:49] - JDBC Connection [HikariProxyConnection@627212314 wrapping org.mariadb.jdbc.MariaDbConnection@2ba23451] will not be managed by Spring 
DEBUG 24-04-17 18:00:07[taskScheduler-1] [o.f.r.N.selectUseMetaDataUrlConnection:137] - ==>  Preparing: SELECT FILE_NM AS fileNm , FILE_TYPE AS fileType , MODI_DATE AS modiDate , USE_YN AS useYn , JOB_STATUS AS jobStatus FROM NVD_META WHERE FILE_TYPE = ? AND FILE_NM = ? AND MODI_DATE = ? AND USE_YN = 'Y' AND JOB_STATUS = 'C' ORDER BY IDX DESC 
DEBUG 24-04-17 18:00:07[taskScheduler-1] [o.f.r.N.selectUseMetaDataUrlConnection:137] - ==> Parameters: NVD_CPEMatchString(String), /rest/json/cpematch/2.0(String), 2024-04-17T09:00:01.467(String) 
DEBUG 24-04-17 18:00:07[taskScheduler-1] [o.f.r.N.selectUseMetaDataUrlConnection:137] - <==      Total: 0 
DEBUG 24-04-17 18:00:07[taskScheduler-1] [org.mybatis.spring.SqlSessionUtils:49] - Closing non transactional SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@3edc8472] 
DEBUG 24-04-17 18:00:08[taskScheduler-1] [jdk.event.security:-1] - X509Certificate: Alg:SHA256withRSA, Serial:4be40b955ad145f1d67fb01aea72f3be116, Subject:CN=*.nvd.nist.gov, Issuer:CN=R3, O=Let's Encrypt, C=US, Key type:RSA, Length:2048, Cert Id:913988287, Valid from:4/1/24, 10:27 AM, Valid until:6/30/24, 10:27 AM 
DEBUG 24-04-17 18:00:08[taskScheduler-1] [jdk.event.security:-1] - X509Certificate: Alg:SHA256withRSA, Serial:912b084acf0c18a753f6d62e25a75f5a, Subject:CN=R3, O=Let's Encrypt, C=US, Issuer:CN=ISRG Root X1, O=Internet Security Research Group, C=US, Key type:RSA, Length:2048, Cert Id:544235253, Valid from:9/4/20, 9:00 AM, Valid until:9/16/25, 1:00 AM 
DEBUG 24-04-17 18:00:08[taskScheduler-1] [jdk.event.security:-1] -  TLSHandshake: services.nvd.nist.gov:443, TLSv1.3, TLS_AES_256_GCM_SHA384, 913988287 
DEBUG 24-04-17 18:00:08[taskScheduler-1] [s.n.w.p.http.HttpURLConnection:-1] - sun.net.www.MessageHeader@346c52466 pairs: {**GET /rest/json/cpematch/2.0?resultsPerPage=2000&startIndex=0** HTTP/1.1: null}{x-api-key: 0dc1b6f1-8d0c-454f-b4f8-be97c2327b3e}{User-Agent: Java/11.0.21}{Host: services.nvd.nist.gov}{Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2}{Connection: keep-alive} 
DEBUG 24-04-17 18:00:08[taskScheduler-1] [s.n.w.p.http.HttpURLConnection:-1] - sun.net.www.MessageHeader@27b46f5a11 pairs: {null: **HTTP/1.1 404**}{message: **resultsPerPage parameter cannot exceed 500.**}{x-frame-options: SAMEORIGIN}{access-control-allow-origin: *}{access-control-allow-headers: accept, apiKey, content-type, origin, x-requested-with}{access-control-allow-methods: GET, HEAD, OPTIONS}{access-control-allow-credentials: false}{date: Wed, 17 Apr 2024 09:00:08 GMT}{content-length: 0}{apikey: No}{strict-transport-security: max-age=31536000}

**Comment by hyeinlee00** [comment]
@mooli8342 님, 아직 변경된 소스가 main에 반영되진 않았지만, 내부적으로 아래와 같이 변경해서 호출하고 있으니 참고 부탁드립니다.
https://github.com/fosslight/fosslight/commit/fa0e436ed9ebbddd9948f5dd06670a9c3f4bf904

**Comment by vampard** [comment]
안녕하세요 코드 수정 후 배포 아직 안되었을까요? 1.6.3 사용하고 있는데 저도 동일한 에러 발생으로 NVD를 받지 못하고 있습니다.

**Comment by hyeinlee00** [comment]
@vampard 안녕하세요, 해당 commit은 v2.0.0.pre-release버전부터 반영되었습니다.

v2.0.0.pre-release에 몇가지 에러사항이 v2.0.1.pre-release에서 수정되었으므로, 가능하면 v2.0.1.pre-release를 사용해서 확인해주시면 감사하겠습니다.

**Comment by hyeinlee00** [comment]
@mooli8342 님, 위에 남긴 comment와 같이 v2.0.0.pre-release버전부터 해당 이슈가 수정된 commit이 반영되었습니다.
