### ISSUE TITLE
Error: 1146-42S02: Table 'fosslight.USER_COLUMNS' doesn't exist

### ISSUE THREAD

**Issue by vampard** [fosslight/fosslight#1051]
Hello, I am one of fosslight users.

I came accross the error as below when I tried to create a project. I hope someone could help me solve this issue. 
- it was my first login after installing the app through docker compose up --build
- my os is Ubuntu 22.04.3 LTS
- fosslight version: 2.0.0_pre version
- no internet condition

**reproduce path**
- docker compose build > when clicking project menu with login through admin
- same error when clicking self check

the error shown up is like this below
WARN  24-07-09 10:46:17[http-nio-8180-exec-1] [o.m.jdbc.message.server.ErrorPacket:100] - Error: 1146-42S02: Table 'fosslight.USER_COLUMNS' doesn't exist

**reproduce path**
- docker compose build > when creating project menu with login through admin

the error shown up is like this below
WARN  24-07-09 10:46:17[http-nio-8180-exec-8] [o.m.jdbc.message.server.ErrorPacket:100] - Error: 1054-42S22: Unknown column 'T1.DESTRIBUTION_STATUS' in 'field list'
ERROR 24-07-09 10:46:17[http-nio-8180-exec-8] [o.f.service.impl.ProjectServiceImpl:260] -
### Cause: java.sql.SQLSyntaxErrorException: (conn=6) Unknown column 'T1.DESTRIBUTION_STATUS' in 'field list'
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: (conn=6) Unknown column 'T1.DESTRIBUTION_STATUS' in 'field list'

**Comment by hyeinlee00** [comment]
Hello @vampard, 
You already closed this issue, but I want to let you know that user_columns issue can be resolved, if you adjust this commit: [d8060a8](https://github.com/fosslight/fosslight/commit/d8060a8e6e8be1bf37b7cfac02de3c17b3362a61)

Also, "DESTRIBUTION_STATUS" error was fixed if you use fosslight_create.sql in v2.0.1.pre-release.
