### ISSUE TITLE
Comment History only shows in packaging tab.

### ISSUE THREAD

**Issue by su-ram** [fosslight/fosslight#106]
**Describe the bug**
`Comment History` only shows in `packaging` tab. 

**To Reproduce**
when you click the `Show Comment History` button in `packaging` tab. 

**Expected behavior**
Comment history supposed to be showed up in identification tab and packaging tab both. 
![fosslight_comment_ok](https://user-images.githubusercontent.com/20367043/131257873-5e2bae2e-f215-4193-8d90-70aee342adf7.PNG)
The past comments has to be showed up like this. 

**Screenshots**
![fosslight_comment_bug](https://user-images.githubusercontent.com/20367043/131257851-0fb9c342-8655-4d68-9037-1d143eabb0b8.PNG)
`Identification` tab shows none of the comments. 

**System Environment (please complete the following information):**
 - Browser chrome
 - Version 92.0.4515.159 (64bit)
 - Etc

**Additional context**

**Comment by soimkim** [comment]
@su-ram , do you want to f/u this issue? 
If you don't f/u, I'll add it to the contribution item so someone can assign it.
