### ISSUE TITLE
Packing에서 Verify클릭시 path not found 발생 이슈 - 가이드 수정 요청

### ISSUE THREAD

**Issue by vampard** [fosslight/fosslight#1067]
안녕하세요 

비슷한 맥락이지만, 별도의 이슈라 분리하여 업로드합니다. 

application.properties에서 verify 실행파일의 경로를 맞춰줘도 packing에서 path not found와 같은 메시지가 계속 뜨면서 
verify가 안되는데요. 

원인은 verify 스크립트에 보시면 아래와 같이 tree라는 모듈을 사용하기 때문에 그렇습니다. 

저처럼 리눅스를 설치하고 난 후 Fosslight를 사용할 경우 tree는 기본 모듈이 아니라 제 서버에 설치한 적이 없으니 스크립트가 제대로 동작하지 않은 것 같습니다.

#Verify Check File List
echo $4 | sed -e "s/\@\@/ /g" >> $6/output/$2/verify_chk_list_$5
**tree** -Ffi $6/decompression/$2/  >> $6/output/$2/verify_chk_list_$5

아래와 같이 tree 모듈을 저장소로부터 설치를 하니 에러없이 동작하네요. 
# sudo apt-get install tree 

이러한 내용은 fosslight 설치 가이드에 없는데, 
다른 사용자들도 동일한 문제를 겪지 않으려면 가이드에 tree도 함께 설치되어야 한다는 내용이 있는 것이 좋을 듯합니다. 

https://fosslight.org/fosslight-guide-en/features/1_developer.html#how-to-install---2

검토부탁드립니다. 

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System Environment (please complete the following information):**
 - Etc

**Additional context**

**Comment by hyeinlee00** [comment]
@vampard 님, 좋은 의견 감사합니다.
docker image를 사용해서 fosslight hub를 실행하는 경우에도 동일한 이슈가 있어 1.6.4 branch를 통해 업데이트 해두려고 합니다.
(관련 이슈: [#1035](https://github.com/fosslight/fosslight/issues/1035))

또한 의견주신 것과 같이 fosslight.org가이드 페이지 업데이트하도록 하겠습니다.

업데이트되면 comment남겨두도록 하겠습니다.

**Comment by hyeinlee00** [comment]
@vampard 님, 가이드 페이지 업데이트되었습니다: [https://fosslight.org/hub-guide/advanced/1_developer.html](https://fosslight.org/hub-guide/advanced/1_developer.html
)
참고로, fosslight.org에서 FOSSLight Hub가이드와 Scanner가이드가 페이지 분리되어 주소가 변경되었으니 참고해주시기 바랍니다.

혹시 또 가이드페이지에서 추가했으면 하는 의견있으시면 언제든 알려주시기 바랍니다! :)
