### ISSUE TITLE
Prevent nickname on the SRC/BIN tabs from being renamed to OSS name when checked by admin on the BOM tab

### ISSUE THREAD

**Issue by mingukang-kr** [fosslight/fosslight#107]
# Description what problem is
Nickname on the SRC/BIN tab is renamed to OSS name unintentionally even if checked by admin on the BOM tab.

# Screenshot
1. the row checked by admin on BOM tab. (you can see it on the far right)
![img1](https://user-images.githubusercontent.com/40283833/131256755-1bd6cadd-f4c0-48a6-bd88-15b09b5a30b5.png)

2. change OSS name of the row on SRC tab to 'cairo456', another registered OSS name I registered.
![img2-2](https://user-images.githubusercontent.com/40283833/131257521-0e736484-80d1-41e5-9139-53d93bc6970c.png)

3. but, when try to save, you can see the popup suggesting that you rename it to 'cairo', original OSS name.
![img2-3](https://user-images.githubusercontent.com/40283833/131257556-ac83d948-e10f-457b-bad3-39c393afad4b.png)

4. then, when click ok button, it renamed to 'cairo' unintentionally.
![img2-4](https://user-images.githubusercontent.com/40283833/131257636-3bea3253-7e17-42c1-b3c7-68b85cf8a5be.png)

**Comment by soimkim** [comment]
I'm closing this issue because this feature has already been merged.
