### ISSUE TITLE
JSON parsing error that occurs every time receiveMessage method is called.

### ISSUE THREAD

**Issue by ubermen5che** [fosslight/fosslight#133]
**Describe the bug**
First of all, it is not a critical bug in the system. However, this makes debugging difficult. The reason for this error is that the `receiveMessage` method executes the `JSON.parse` method once more for the data, which is a javascript object. To explain in more detail, whenever the method `addEventListener` existing in `../resources/basic/js/basic.js` is called, `receiveMessage` is also called. At this time, the `receiveMessage` method is a callback method and an `event` object is entered as a parameter. In the function, an appropriate function is performed according to the `event.data` value. In the current system, the type of `event.data` may be `object` or `string`. However, in the previous code, the error occurred because the object type data was once again tried to be a javascript object using the `JSON.parse` method.

**To Reproduce**
This is a problem that applies to all parts of the current FOSSLight service that are the scope of the call target of addEventListener.

**Expected behavior**
It is expected that all error messages that occur will be removed.

**Screenshots**
![image](https://user-images.githubusercontent.com/76172759/133768600-d59138e3-9c2f-4ab9-918f-7db7fe9620a6.png)

**System Environment (please complete the following information):**
 - Chrome
 - 93.0.4577.82
 - MacOS Bigsur 11.4
 
**Additional context**
I suggest the code below.
```
function receiveMessage(event) {

	var data = event.data;

	if (typeof data === 'object') {
	}
	else if (typeof data === 'string') {
		data = JSON.parse(event.data);
	}

	switch(data.action){
		case 'create':
			createTab(data.tabData[0], data.tabData[1]);
			console.log(data.tabData[0] + data.tabData[1]);
			break;
			...
```
current code
```
function receiveMessage(event) {

	var data = event.data;

	switch(data.action){
		case 'create':
			createTab(data.tabData[0], data.tabData[1]);
			console.log(data.tabData[0] + data.tabData[1]);
			break;
			...
```

**Comment by ubermen5che** [comment]
There seems to have been a mistake. The error was caused by an unknown conflict with a chrome extension called 'MetaMask'. Therefore, I would like to inform you that this is not an error that occurs in a common case.

**Comment by soimkim** [comment]
[Deferred]
Crashes when installing some chrome extensions.
