### ISSUE TITLE
Add a function to automatically set the sending target to all and send an email when saving comments

### ISSUE THREAD

**Issue by riyenas0925** [fosslight/fosslight#136]
**Is your feature request related to a problem? Please describe.**
AS-IS : When saving comments, a window appears to select the destination to send mail, and you send mail to the selected target.
TO-BE : When saving comments, set the sending target to all and send an email when saving comments

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/32615702/133890036-88fc5eb9-5235-4d7b-abd2-a32d05dce34e.png)

**Comment by soimkim** [comment]
@riyenas0925 ,
How about changing the alert message?
"Command has been sent." -> "Your message has been sent."

**Comment by riyenas0925** [comment]
@soimkim 
That seems to make more sense! 👍 
I will change the requirements for contribution items

**Comment by riyenas0925** [comment]
@soimkim 
conflict resolved 😄
