### ISSUE TITLE
Delete duplicate buttons in identifying a project

### ISSUE THREAD

**Issue by wkdalsgh192** [fosslight/fosslight#138]
**Is your feature request related to a problem? Please describe.**
I was always confused that I saw two groups of buttons that look exactly same on the Identification page when I tried to identify my projects. 

![image](https://user-images.githubusercontent.com/50606172/134138153-f62c997c-ace5-4dc3-8faf-c0b0e96b0ccd.png)

**Describe the solution you'd like**
They technically work same so I think it'd be better to delete one of them to clarify its function, which should be on the upper side of OSS table. Then, the number of files on the table won't be a problem.
![image](https://user-images.githubusercontent.com/50606172/134139376-53092f8d-a31a-4973-9282-a59e01a58c30.png)

**Describe alternatives you've considered**
Keep the below buttons on to be revealed out when you scroll up and down.

**Comment by soimkim** [comment]
It was fixed by leaving only the top button.
