### ISSUE TITLE
Change Self-Check in Obligation Warning message

### ISSUE THREAD

**Issue by Lee-JaeHyuk** [fosslight/fosslight#187]
**Is your feature request related to a problem? Please describe.**
Self-check > Obligation Column > When the mouse hovers over the "?" icon.
- AS-IS: Warning message (ex- "Unconfirmed version) is displayed.
- TO-BE: Display "Obligation is unclear".

![screenshot](https://user-images.githubusercontent.com/60414900/136739698-3eec5f82-c2cb-40bf-ba99-06f73c10c4ce.png)

**Comment by soimkim** [comment]
I close this issue because it will be reflected in PR soon.
