### ISSUE TITLE
Add function OSS, License bulk registration

### ISSUE THREAD

**Issue by ubermen5che** [fosslight/fosslight#188]
**Is your feature request related to a problem? Please describe.**
Currently, when registering OSS and License in the admin page, they are to be registered one by one. Sometimes an administrator may want to register multiple OSSs and licenses at once. Therefore, we propose the following functions.

- Ability to upload files containing OSS and License registration information
- The function to read the uploaded file and save it to the DB(including duplication check)

**Coworkers**
- @acafela
- @doggai10

**Comment by soimkim** [comment]
Dear @ubermen5che ,
Are there any commits made so far?
Another developer wants to F/U on this issue.
