### ISSUE TITLE
Create a UI for issuing OSS Notice in Self-Check.

### ISSUE THREAD

**Issue by JoHyoju04** [fosslight/fosslight#196]
**Is your feature request related to a problem? Please describe.**
Add “OSS Notice” issuance function in Self-check.

**Describe the solution you'd like**
Create button and tab in Self-Check that can issue OSS Notice. (Create a UI for issuing OSS Notice)

**ScreenShots**
-notice button
![버튼 생성2](https://user-images.githubusercontent.com/47858282/137139515-21029cd7-f6db-4750-9a7b-ddef920c7ffe.jpg)

-notice tab
![notice tab 생성](https://user-images.githubusercontent.com/47858282/137139593-e403f101-07ba-46ce-91f0-3209861bfba0.JPG)

**Comment by soimkim** [comment]
@JoHyoju04 , It is really cool!!! 
Let's change the button name from "Notice" to "OSS Notice".

**Comment by soimkim** [comment]
I close this issue because the draft has been merged.
