### ISSUE TITLE
Detected License is not separated by , in the mail sent when OSS is newly registered

### ISSUE THREAD

**Issue by soimkim** [fosslight/fosslight#197]
**Describe the bug**
Detected License is not separated by ',' in the mail sent when OSS is newly registered.
![image](https://user-images.githubusercontent.com/4284712/137230067-ac7d5534-9793-4166-8d48-792672a9f466.png)

**To Reproduce**
OSS List > Click the "Add" button. > Enter two or more licenses to the detected license.
You can check the sent mail in the Sent Mail List.
![image](https://user-images.githubusercontent.com/4284712/137230167-471c2c72-71f5-4754-831e-b7b4c2ef798b.png)

**Expected behavior**
When sending OSS information related mail, if there are two or more Detected Licenses, they should be separated by ,.

**Comment by k2heart** [comment]
Agreed.
