### ISSUE TITLE
Demo site returns 504 Error : Gateway Timeout 

### ISSUE THREAD

**Issue by fu7mu4** [fosslight/fosslight#2]
**Describe the bug**
[The Demo site](https://demo.fosslight.org/) returned 504 Gateway Timeout ,23:48 JST 5th June

**To Reproduce**
Steps to reproduce the behavior: Try to access the Demo site by using Firefox on macOS

**Expected behavior**
The fosslight's sign up screen are shown.

**Screenshots**
<img width="1021" alt="スクリーンショット 2021-06-05 23 53 21" src="https://user-images.githubusercontent.com/1885537/120895766-73ac6900-c659-11eb-82d1-a6622d79e35a.png">

**System Environment (please complete the following information):**
 - Browser Firefox
 - Version 89.0
 - Etc OS macOS Big Sur 11.4

**Additional context**

**Comment by soimkim** [comment]
Thanks for letting us know! 
We've restored https://demo.fosslight.org now.

**Comment by fu7mu4** [comment]
Thanks ! @soimkim
