### ISSUE TITLE
Dummy page in OSS List

### ISSUE THREAD

**Issue by yugeeklab** [fosslight/fosslight#227]
**Describe the bug**
There is only 7 elements when I search OSS with Licence type "Week Copyleft". But the length of pages is 2.

**To Reproduce**

1. Login with admin
2. Go to OSS List
3. Set Licence Type to "Weak Copyleft"
4. Click Search

**Expected behavior**
the length of page is 1.

**Screenshots**
![image](https://user-images.githubusercontent.com/16485416/138889360-5f82e893-1f74-400e-8bcd-d34059986dbc.png)
![image](https://user-images.githubusercontent.com/16485416/138889736-5a70abd6-6171-44e3-84ea-61ff6d023a6e.png)

**System Environment (please complete the following information):**
 - Browser [e.g. chrome, safari] : Chrome
 - Version [e.g. 22] : 95.0.4638.54
 - Etc

**Additional context**
Need to update OSSMapper.

**Comment by soimkim** [comment]
Since this bug has been fixed, I close this issue.
