### ISSUE TITLE
System Mail Error Occurred

### ISSUE THREAD

**Issue by dongs0** [fosslight/fosslight#232]
**Describe the bug**
Automatic mail fails in the system as shown below.

"Mail server connection failed; nested exception is com.sun.mail.util.MailConnectException: Couldn't connect to host, port: localhost, 25; timeout -1; nested exception is: java.net.ConnectException: Connection refused (Connection refused). Failed messages: com.sun.mail.util.MailConnectException: Couldn't connect to host, port: localhost, 25; timeout -1; nested exception is: java.net.ConnectException: Connection refused (Connection refused) "

**To Reproduce**

1. SMTP Setting
![image](https://user-images.githubusercontent.com/60166229/139384107-253f0f84-0bd5-45e9-8e9d-df799d45b905.png)

2. How to FOSSLight Hub Run
1) Dockerfile, docker-compose.yml File Edit
  Due to the docker rate issue, change the image tag part of the above configuration files to a tag that can be received as a mirror within the internal and install it

2) docker-compose up --build

**Expected behavior**
Send mail normally

**Screenshots**
![image](https://user-images.githubusercontent.com/60166229/139384708-4a4b0ab1-788d-4161-af34-7cbd3f8f28c5.png)

**System Environment (please complete the following information):**
 - Browser : chrome
 - Version : 95.0.4638.69

**Comment by soimkim** [comment]
@dongs0 ,
Note that you need to restart the FOSSLight Hub after SMTP setting.

It seems to be caused by you editing docker-compose.yml.
This is an issue that cannot be reproduced in the current version.

**Comment by dongs0** [comment]
![image](https://user-images.githubusercontent.com/60166229/145313723-49ca4ba7-9a0e-49a9-b2d9-b22e81a457bf.png)

Sorry I missed the comment.
yml file, like the attached captured image.
Changed only tags that receive image to in-house. No edits other than that
