### ISSUE TITLE
OSS detailed information mail > OSS version change

### ISSUE THREAD

**Issue by soimkim** [fosslight/fosslight#234]
OSS detailed information mail > OSS version notation change

1.` OSS Version` -> Change to ` OSS Version / OSS Type`
2. If there is nothing to output OSS type in the 'Registered Data' field, modify not to output `/`.

![image](https://user-images.githubusercontent.com/4284712/139399705-fe378bfe-88ae-440a-a90e-ee75141de5b2.png)

**Comment by qkrdmstlr3** [comment]
@soimkim 
Is this issue currently valid?

**Comment by soimkim** [comment]
@qkrdmstlr3 ,
Thanks for asking. 😄 
This issue has been fixed. When sending OSS-related information mail, OSS type format has been unified.
