### ISSUE TITLE
Identification > Add tool usage guide for each tap(SRC,BIN)

### ISSUE THREAD

**Issue by bjk7119** [fosslight/fosslight#280]
**Is your feature request related to a problem? Please describe.**
To add a guide to clearly guide the user on which tool to use on each tab.

**Describe the solution you'd like**
Add user guide button
 - If user hover mouse on the button, the message with short description will appear.
 - If user click the button, the user guide page of the tool used for each tab in Github will be opened.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by soimkim** [comment]
@bjk7119 , Which URL should I link to for each tab?

**Comment by bjk7119** [comment]
@soimkim ,
Well, I thnk https://fosslight.org/fosslight-guide-en/scanner/ would be good for the conntected url.
And it would be better to show which tool to use in the message when user hover mouse.

**Comment by soimkim** [comment]
As the UI is scheduled to be completely reorganized, this issue will be closed as Deferred.
