### ISSUE TITLE
an issue occured during the version upgrade process

### ISSUE THREAD

**Issue by dongs0** [fosslight/fosslight#326]
**Describe the bug**
--------
building web
error checking context: 'no permission to read from '/home1/irteamsu/fosslight/mail/mailstate/spool-postfix/dev/random''.
ERROR: Service 'web' failed to build : Build failed

**To Reproduce**
--------

The upgrade was performed by the following process.
1) git pull to the existing path
2) docker container all stop
3) docker rm [fosslight_web container]
4) docker rmi [fosslight_web image]
5) docker-compose up --build
 
After that, the error message occurs.

**System Environment (please complete the following information):**
--------
 - CentOS

**Additional context**
--------
If I download and run fosslight in a separate path, the build works normally, but an error occurs where there is existing data..

**Comment by soimkim** [comment]
@dongs0 , 
The folder created for the docker mail service, `/home1/irteamsu/fosslight/mail/`, does not seem to have permission. 
Delete the `/home1/irteamsu/fosslight/mail/` folder and try running it again.
