### ISSUE TITLE
Suggest changing the use of the 'indexOf' method to 'contains'

### ISSUE THREAD

**Issue by greeenly** [fosslight/fosslight#33]
**Is your feature request related to a problem? Please describe.**
`indexOf` methods are used in several classes, including `src/main/java/oss/fosslight/controller/AdviceController.java`.

**Describe the solution you'd like**
I think it is appropriate to use `contains` rather than `indexOf` because the method only checks for existence.
Also, I think using `contains` is better in terms of readability.

**Describe alternatives you've considered**
I referred to [this link](https://stackoverflow.com/questions/10714376/which-string-method-contains-or-indexof-1).

**Comment by soimkim** [comment]
I agree with your opinion. 
Let's change  `indexOf `, which checks only whether String contains or not, to `contains`.
