### ISSUE TITLE
Hide the Check License, Check OSS Name buttons with the same conditions as the Save button.

### ISSUE THREAD

**Issue by soimkim** [fosslight/fosslight#341]
Hide the `Check License`,` Check OSS Name` buttons with the same conditions as the `Save `button.

* Reason for need: If you don't click Save, the button doesn't work, so you need to hide it like the Save button.

* TO-BE: Identification (SRC, BIN) of the Project, Check OSS Name and Check License button in Self-check are set identically to the display conditions of the Save button.

**Comment by Zeusjonass** [comment]
I'll work on this issue if it's ok for you :)
