### ISSUE TITLE
log cannot be resolved

### ISSUE THREAD

**Issue by mehtaketan1511** [fosslight/fosslight#347]
Hello,

**Describe the bug**
I am trying to setup the this Framework on my local machine using https://fosslight.org/fosslight-guide-en/features/1_developer.html#build-and-run guide 

I am following the How to Install -2 Option, workspace and db setup properly but facing the problem in log.info(lombok-1.18.8.jar)
Kindly request you to please find the below screenshot for more details.

**Screenshots**
![image](https://user-images.githubusercontent.com/26324142/146348495-14f482e8-ea4f-48a2-812c-a3777264f0e8.png)

**System Environment (please complete the following information):**
 Same as per the  How to Install -2 Option suggestion

Please suggest how to fix this issue !!

Thank you in Advance !!

**Comment by soimkim** [comment]
@mehtaketan1511 , Is lombok installed?
![image](https://user-images.githubusercontent.com/4284712/146477014-c4a65255-f1d0-4138-9289-663d44698cb6.png)

**Comment by soimkim** [comment]
@mehtaketan1511 ,
If an error occurs even after adding the file, please reopen the issue. 😃
