### ISSUE TITLE
Add 'restart: always' option in docker-compose

### ISSUE THREAD

**Issue by epicarts** [fosslight/fosslight#35]
**Is your feature request related to a problem? Please describe.**

fosslight_db(db) container has `restart: always` option, but fosslight_web(web) hasn't.

I think fosslight_web have to restart in case of a crash. 

**Describe the solution you'd like**
Add 'restart: always' option in fosslight_web container of docker-compose

**Comment by epicarts** [comment]
### Enable restart option 
```
PID   USER     TIME  COMMAND
    1 root      3:41 java -jar FOSSLight.war --root.dir=/data/fosslight --server.port=8180 --spring.datasource.url=db:3306/fosslight --spring.datasource.username=fosslight --spring.datasource
   86 root      0:00 /bin/sh
  112 root      0:00 ps -ef
/ # kill 1
```
when i killed pid 1

```
fosslight_web  | INFO  21-08-09 16:41:03[Thread-3] [org.ehcache.core.EhcacheManager:216] - Cache 'tlshDistanceDbCache' removed from EhcacheManager.
fosslight_web  | INFO  21-08-09 16:41:03[Thread-3] [org.ehcache.core.EhcacheManager:216] - Cache 'autocompletePartnerCache' removed from EhcacheManager.
fosslight_web exited with code 143
fosslight_db   | 2021-08-10  1:41:04 14 [Warning] Aborted connection 14 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.3' (This connection closed normally without authentication)
fosslight_web  | 
fosslight_web  |  _______  _______  _______  _______  ___      ___   _______  __   __  _______ 
fosslight_web  | |       ||       ||       ||       ||   |    |   | |       ||  | |  ||       |
fosslight_web  | |    ___||   _   ||  _____||  _____||   |    |   | |    ___||  |_|  ||_     _|
fosslight_web  | |   |___ |  | |  || |_____ | |_____ |   |    |   | |   | __ |       |  |   |  

```
It automatically restart.

### Disable restart option 

```
fosslight_web  | INFO  21-08-09 16:48:40[Thread-3] [org.ehcache.core.EhcacheManager:216] - Cache 'ossInfoCache' removed from EhcacheManager.
fosslight_web  | INFO  21-08-09 16:48:40[Thread-3] [org.ehcache.core.EhcacheManager:216] - Cache 'tlshDistanceDbCache' removed from EhcacheManager.
fosslight_web  | INFO  21-08-09 16:48:40[Thread-3] [org.ehcache.core.EhcacheManager:216] - Cache 'autocompletePartnerCache' removed from EhcacheManager.
fosslight_web exited with code 143
```

In this case, the web container is terminated forever.

**Comment by soimkim** [comment]
Dear @epicarts ,
If PR occurs, we check whether the login page is accessible after build to check if the service boots well.
- https://github.com/fosslight/fosslight/blob/develop/.github/workflows/pull-request.yml 

However, if the restart option is added, it is restarted even if the service dies during booting, so it is difficult to check whether an error has occurred.

There is little change in DB, but there are many changes in web service, so it is necessary to check the reason when the service is terminated.

**Comment by epicarts** [comment]
I missed that GitHub Action use docker-compose.
Thanks for comment :)

I tested in two situations.
In one case, gradle build failed, and in other case runtime application run failed.


## gradle build failed

Refer to [restart-policy](https://docs.docker.com/config/containers/start-containers-automatically/#restart-policy-details) in Docker doc.

`starting successfully means that the container is up for at least 10 seconds and Docker has started monitoring it. This prevents a container which does not start at all from going into a restart loop.`

If docker-compose build is a failure, web container not run and not restarted. Also the spring server does not even run.


## Application run failed

Invalid database information in docker-compose. And then PR.
- https://github.com/epicarts/fosslight/pull/3/checks?check_run_id=3292715723

### Build the stack
```
Successfully built a2d74b3c2e9b
Successfully tagged fosslight_web:latest
Creating fosslight_db ... 
Creating fosslight_db ... done
Creating fosslight_web ... 
Creating fosslight_web ... done
```
In the 'Build the stack' step, when the docker container is created, it moves on to the next step.

### Check running containers
```
  docker-compose ps
  shell: /usr/bin/bash -e {0}
    Name                   Command                 State                       Ports                  
------------------------------------------------------------------------------------------------------
fosslight_db    docker-entrypoint.sh mysqld      Up           0.0.0.0:3306->3306/tcp,:::3306->3306/tcp
fosslight_web   sh -c ./wait-for db:3306 - ...   Restarting        

```
In the 'Check running containers' step, can see that state is restarting.

### Check the site
```
docker: Error response from daemon: Container 44a750cd18e91919cb928e153b21a08571d76986d8e5e19ff553bb53736bba75 is restarting, wait until the container is running.
```
In the 'Check the site ' step, it is restarting. so this step failed.


## Summary
Both gradle build and Application run steps catch a failure. It seems that there will be no problem with github action.

Refer to [Use Compose in production doc](https://docs.docker.com/compose/production/#modify-your-compose-file-for-production). 
In a production environment, `Specifying a restart policy like restart: always to avoid downtime`

But ‘restart: always’ not necessary unless to run the web service all the time.

I'd like to hear your opinion. Thank you for reading.

**Comment by soimkim** [comment]
@epicarts ,
It's good to see the test result.

However, like the last comment you left, it is an option necessary to keep the web service always running.
And we still plan to fix a lot of modifications to the web service, and it is necessary to quickly identify the cause when the service is terminated.

So, how about adding `restart: always` later when the web service is stable?

**Comment by epicarts** [comment]
I agree with you. 
Thanks you for comment :)
