### ISSUE TITLE
gradle wrapper(gradlew) need to add execution permission

### ISSUE THREAD

**Issue by epicarts** [fosslight/fosslight#36]
**Is your feature request related to a problem? Please describe.**
```
> ./gradlew
zsh: permission denied: ./gradlew
```
gradlew is not execution in this project.

```
> ls -al gradlew
-rw-r--r--  1 epicarts  staff  5960  8 10 02:10 gradlew
```
gradlew hasn't `x` permission.

**Describe the solution you'd like**
Change file permission `-rw-r--r--`(644)  to `-rwxr-xr-x`(755).

**Describe alternatives you've considered**

https://start.spring.io/  
The permission generated on this site is `-rwxr-xr-x`

https://github.com/spring-projects/spring-boot
This spring project has `-rwxr-xr-x`

**Comment by soimkim** [comment]
Dear @epicarts ,
I agree with you. 
Please modify the permission of gradlew.

**Comment by soimkim** [comment]
@epicarts , Thanks for Contribution.
