### ISSUE TITLE
Cannot create user's division in admin

### ISSUE THREAD

**Issue by namkyu1999** [fosslight/fosslight#37]
**Describe the bug**
When I sign in fosslight system as an Admin, Admin can administrate user in [System>User management] tab. But Admin can't create divsion. So Admin cannot set user's division. Is there any way to create division?

**To Reproduce**
- Add functions to create divsion.
- Add UI in [System>User management] tab.

**Expected behavior**
When someone signed in as an Admin, Admin can create divsion in [System>User management] tab. 

**Screenshots**
![division](https://user-images.githubusercontent.com/53862866/128804557-e19e0e3a-40c7-4aa9-b0ed-94aa84cd7ad8.png)

**Comment by soimkim** [comment]
![image](https://user-images.githubusercontent.com/4284712/128806469-d35385c8-01de-4c46-8b8c-86c7ca6a48e3.png)
Division can be added, modified, or deleted in Code Management > Code Name: Division.

**Comment by namkyu1999** [comment]
I found it! and everything is okay. thanks:)
