### ISSUE TITLE
The default tab that is displayed when logged on FOSSLight Hub

### ISSUE THREAD

**Issue by bjk7119** [fosslight/fosslight#379]
**Is your feature request related to a problem? Please describe.**
Whenever connecting the FOSSLight Hub, I hope the tab selected by the user appears first.

**Describe the solution you'd like**
Add to check box to select user preferred default tab.

**Describe alternatives you've considered**

**Additional context**
Currently, the last tab among the tabs selected in the Default Tab menu is displayed when user logged on FOSSLight Hub.
However, the default tab preferred by each user is different.
So, it would be better if the preferred Default Tab set by the user appears first when user logged on the site.

**Comment by soimkim** [comment]
@bjk7119 , If you click the logged-in user name in the left menu, you can set the default tab in the User settings tab.
Please make sure your request is satisfied.
