### ISSUE TITLE
Typo in Class

### ISSUE THREAD

**Issue by kimtaehyun98** [fosslight/fosslight#39]
**Is your feature request related to a problem? Please describe.**
I found the typo "encordedFilename" in a DownloadProcController.java

**Describe the solution you'd like**
change value name "encordedFilename" to "encodedFilename"

**Comment by soimkim** [comment]
@kimtaehyun98 , Let's fix it. :-)

**Comment by soimkim** [comment]
@kimtaehyun98 , Thanks for Contribution.
