### ISSUE TITLE
Change that Reviewer can change status to Reopen/Complete by no comment

### ISSUE THREAD

**Issue by kimtaehyun98** [fosslight/fosslight#42]
**Is your feature request related to a problem? Please describe.**

Currently, if reviewer wants to change project status to "Reopen/Complete", reviewer must comments. 

**Describe the solution you'd like**

In the Project List > change status button, when the reviewer clicks the Reopen/Complete button, it can be OK even if nothing is written in the comment.

**Comment by soimkim** [comment]
- Reviewer : User with Admin privileges.
- Reopen : Restart Identification

**Comment by soimkim** [comment]
Dear @kimtaehyun98 ,
Please check this function again. It's not working. 🥲
![image](https://user-images.githubusercontent.com/4284712/130308603-990e0aab-5f50-4f59-a8f5-bff7c9e8cc03.png)

When I click Project List > Change Status to complete, a pop-up asking me to enter a comment appears if I did not enter a comment.

**Comment by kimtaehyun98** [comment]
Dear @soimkim 
Thanks to Check!😁

I found that my pr is not reflected.

First, this is my pr.

![image](https://user-images.githubusercontent.com/65909160/130310832-a96e6cd0-2fac-4171-945b-85841f6ff6e4.png)

I create "commentFlag" value and validation logic.

But in the code, I can't find this change.
![image](https://user-images.githubusercontent.com/65909160/130310817-5043c7e9-eb36-420d-b41d-a9c6df709029.png)

It may be invisable in my case, Can you check this part? 
Thanks!

**Comment by kimtaehyun98** [comment]
@soimkim
I find why function is not working!😁

After my pr, Fosslight-dev account is commit to same file
![image](https://user-images.githubusercontent.com/65909160/130322940-c6162043-e80f-409e-aa9b-833790933aad.png)

And that commit is not reflect my pr, so it seems cover my pr.
![image](https://user-images.githubusercontent.com/65909160/130322970-bd316c81-634a-41f5-8145-ad1326c31e2e.png)

In this case, how to deal with? Is it ok to pr again?
Thanks to comment!

**Comment by soimkim** [comment]
@kimtaehyun98 ,
OMG. I’m so sorry. 
I will cherry-pick your commit again. 🙂

**Comment by soimkim** [comment]
@kimtaehyun98 ,
I re-pushed your commit to branch:develop.
Thank you for checking.
