### ISSUE TITLE
If user hover the mouse over the 'project name' in the 'project list', change it to a pointer icon.

### ISSUE THREAD

**Issue by soimkim** [fosslight/fosslight#432]
**Is your feature request related to a problem? Please describe.**
If user hover the mouse over the 'project name' in the 'project list', change it to a pointer icon.
- The reason this function is needed: To inform that the project name cell is clickable.

**Comment by qkrdmstlr3** [comment]
@soimkim May I try to solve this issue?

**Comment by soimkim** [comment]
@qkrdmstlr3 , I assigned this issue to you.
Thanks for volunteering to contribute! 😃
