### ISSUE TITLE
Search after removing spaces before and after the search word in the OSS List.

### ISSUE THREAD

**Issue by soimkim** [fosslight/fosslight#441]
In the OSS List, if there is a space before or after the search word for OSS Name, License Name, or Website, remove it and search.

**Comment by coding-Benny** [comment]
@soimkim May I try this one?

**Comment by soimkim** [comment]
@coding-Benny , I assigned this issue to you.
Thanks for volunteering to contribute! 😄

**Comment by MiniVee** [comment]
@soimkim , Can I take this issue?
