### ISSUE TITLE
If user hover the mouse over the 'project name' in the 'project list', show tooltip text "Double click"

### ISSUE THREAD

**Issue by soimkim** [fosslight/fosslight#447]
If user hover the mouse over the 'project name' in the 'project list', show tooltip text "Double click"

Why FOSSLight Hub need this feature:
- The project name should be double-clicked to prevent misunderstanding that there is no function when clicking once.

**Comment by MyunghyunNero** [comment]
can i try this issue?😊

**Comment by soimkim** [comment]
@MyunghyunNero , yep!! 😄
