### ISSUE TITLE
Tabs should not be moved after 'Change License'.

### ISSUE THREAD

**Issue by soimkim** [fosslight/fosslight#457]
**Is your feature request related to a problem? Please describe.**
Tabs should not be moved after the `Change License `operation. However, there is a problem of moving to the previous tab after Change License.

**How to reproduce**
1. Create a project.
2. Go to SRC tab in Identification column.
3. Write anything and then click save.
4. Go to BIN tab.
5. Add the following row.
    - OSS Name : fosslight_util, Download location : https://github.com/fosslight/fosslight_util
    ![image](https://user-images.githubusercontent.com/4284712/160228845-aa22a709-137f-4619-913f-89783db6c0cd.png)
6. Click the save button.
7. Click the 'Change License' button.
8. Click `Change License` in the pop-up.
9. Then, the BIN tab should be visible, but it has been moved to the previous tab, the SRC tab.

**Comment by FRESH-TUNA** [comment]
@soimkim I think this issue should be closed.
Because improvement code is merged with pull request #568.
Have a good night, thanks!
