### ISSUE TITLE
Mouse hover over the name at the top of the left menu, show the user's name.

### ISSUE THREAD

**Issue by soimkim** [fosslight/fosslight#458]
**Is your feature request related to a problem? Please describe.**
If you mouse over the name at the top of the left menu, User Settings is displayed.
![image](https://user-images.githubusercontent.com/4284712/160317579-5bae1028-d721-4ff2-ae8e-7a213ea094a6.png)

However if the user name is long, it will be truncated.

**Describe the solution you'd like**
Therefore, when user mouse hover over the name at the top of the left menu, show the `user's name` instead of `User Settings`.

**Comment by zshawdev** [comment]
Hello, I'd like to help with this one! Would I be able to get assigned to it?

**Comment by soimkim** [comment]
@zshawdev , I assigned this issue to you.
Thanks for volunteering to contribute! 😃

**Comment by MyunghyunNero** [comment]
can i try this issue? 😊😃

**Comment by hataerin** [comment]
Hi👋 Can I take this issue?
