### ISSUE TITLE
Project's Basic Information > Increase the length of the name field

### ISSUE THREAD

**Issue by soimkim** [fosslight/fosslight#459]
**Is your feature request related to a problem? Please describe.**
Project's Basic Information > Increase the length of the name field.
- Project's Basic Information : Double-click the project name in the Project List.

**Describe the solution you'd like**
1. In the Watcher column, increase the length of the red box below to the size of the green box.
2. Increase the length of the Creator and Reviewer by the red box.
![image](https://user-images.githubusercontent.com/4284712/160318595-36c3440c-e576-4ad1-a99f-5d176b3a154d.png)

**Comment by shlev** [comment]
Hi , May i ?

**Comment by soimkim** [comment]
@shlev , I assigned this issue to you.
Thanks for volunteering to contribute! 😃

**Comment by MiniVee** [comment]
@soimkim Can I take this issue? 😀

**Comment by soimkim** [comment]
@MiniVee, I assigned this issue to you. 😃
