### ISSUE TITLE
3rd Party's Basic Information > Increase the length of the name field

### ISSUE THREAD

**Issue by soimkim** [fosslight/fosslight#460]
**Is your feature request related to a problem? Please describe.**
3rd Party's Basic Information > Increase the length of the name field.

3rd Party's Basic Information : Double-click the 3rd Party name in the 3rd Party List.

**Describe the solution you'd like**
1. In the Watcher column, increase the length of the red box below to the size of the green box.
2. Increase the length of the Creator and Reviewer by the red box.
![image](https://user-images.githubusercontent.com/4284712/160318836-f12c6c50-faf8-4b9b-87b0-f586f9255c1c.png)

**Comment by zshawdev** [comment]
Hello @soimkim, I'd like to help with this one! Would I be able to get assigned to it?

**Comment by soimkim** [comment]
@zshawdev , I assigned this issue to you.  😃
