### ISSUE TITLE
Change the FOSSLight image to the latest version.

### ISSUE THREAD

**Issue by soimkim** [fosslight/fosslight#461]
**Describe the solution you'd like**
Change the FOSSLight image to the latest version.
1. Login Page
   ![image](https://user-images.githubusercontent.com/4284712/160501854-3b1b8e9f-57b7-4f48-ae4e-ba7d069e6c05.png)
2. SignUp page
    ![image](https://user-images.githubusercontent.com/4284712/160501901-638a27d7-fbe7-48c2-a1d6-0e8fe43b7e41.png)
3. Top left menu bar
    ![image](https://user-images.githubusercontent.com/4284712/160501991-29fef301-835e-400d-b0c5-83c3a16caf67.png)

latest image: (You can resize it to fit the displayed size.)
![image](https://user-images.githubusercontent.com/4284712/160502223-4468371c-cc34-43eb-bfa3-80ccef00bab1.png)

**Comment by MoonDD99** [comment]
May I try to solve this issue? @soimkim

**Comment by soimkim** [comment]
@MoonDD99 , I look forward to your contribution. 😃
