### ISSUE TITLE
Translate Comments to English

### ISSUE THREAD

**Issue by wkdalsgh192** [fosslight/fosslight#47]
**Is your feature request related to a problem? Please describe.**
Korean and English are now being mixed up in comments, which may cause misunderstandings of source code to developers.

**Describe the solution you'd like**
Needs to translate all the comments written in Korean to English for a clear description for global contribution.

**Describe alternatives you've considered**
Switching back to Korean(?)

**Additional context**
Related code: https://github.com/fosslight/fosslight/blob/develop/src/main/java/oss/fosslight/domain/CoMailManager.java

-> Think this needs to be labeled as 'chore' or 'documentation'.

**Comment by soimkim** [comment]
@wkdalsgh192 , I am waiting for your contribution. :-)
