### ISSUE TITLE
Display License Official URL instead of Internal URL when creating the NOTICE

### ISSUE THREAD

**Issue by syleeeee** [fosslight/fosslight#482]
**Is your feature request related to a problem? Please describe.**
We had to replace all the internal URLs in the auto-generated NOTICE file because the URL does not work. So it would be great if we can choose which URL we would display in the NOTICE.

**Comment by soimkim** [comment]
@syleeeee , Thanks for the nice idea. 😃 
In the **Notice setting** of Configuration, it would be nice to be able to set whether the **License link** to be included in the OSS Notice publication should be `Website for the license` or `Internal URL`.

**Comment by soimkim** [comment]
Dear @syleeeee , this issue will be fixed at https://github.com/fosslight/fosslight/pull/587.

**Comment by syleeeee** [comment]
Wow can't wait!! Thanks a lot @soimkim 👍
