### ISSUE TITLE
Change the UI for self-check upload

### ISSUE THREAD

**Issue by soimkim** [fosslight/fosslight#485]
**Is your feature request related to a problem? Please describe.**
Change the UI for self-check upload.

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/4284712/164580626-c5bf378c-48df-4709-b0e2-370f5b741af7.png)
- The URL toggle button should be on the right side of Upload Analysis Result.

![image](https://user-images.githubusercontent.com/4284712/164580891-eb41a368-6f42-4f66-afe1-78e47a928cd8.png)
- When the URL is clicked, the Upload Analysis Result toggle should be unchecked.
- When the URL is clicked, the Upload Analysis Result field should be hidden. Just like the input field is hidden when the url is unchecked.

**Comment by suhwan-cheon** [comment]
@soimkim 
hello! long time, no see. Can I take charge of this issue? 😆

**Comment by soimkim** [comment]
@suhwan-cheon, 😄 Nice to see you again!
I look forward to your contribution.
