### ISSUE TITLE
Add to show docker-compose logs in github-actions

### ISSUE THREAD

**Issue by riyenas0925** [fosslight/fosslight#49]
**Is your feature request related to a problem? Please describe.**
We plan to save the log after executing docker-compose --build -d in the github action and display it after the github actions are finished.

**Describe alternatives you've considered**
It will probably save and display docker-compose logs.

**Comment by epicarts** [comment]
I'm concerned docker-compose logs do not show build steps. It just view output from containers. 
I think that listen to the maintainer's opinion.

**Comment by riyenas0925** [comment]
@epicarts @soimkim 

I printed out the contents of container because github actions are showing build log in build the stack stage, and I think it would be better to ask maintainer.

Thank you for your comments 😄

**Comment by riyenas0925** [comment]
@soimkim 

Can you tell me what the build log means exactly?
I think the docker build log is in the build the stack stage, so I displayed the log of docker containers.

Please check the code and PR I changed below, thank you
* https://github.com/fosslight/fosslight/pull/50 (PR #50)
* https://github.com/fosslight/fosslight/runs/3309 800143?check_suite_focus=true (Changed workflow)

**Comment by soimkim** [comment]
@riyenas0925 ,
Build log means `docker-compose up --build`  execution result log in the following file.
- https://github.com/fosslight/fosslight/blob/develop/.github/workflows/pull-request.yml

docker-compose up --build is executed with -d, so the entire log of docker execution is not visible.

What you made PR is exactly what I want. 👍

**Comment by riyenas0925** [comment]
@soimkim 

Thanks for the reply!

Can I delete the word build from the workflow?
ex) Save docker-compose ~~build~~ logs, Show db container ~~build~~ log, Show web container ~~build~~ log

**Comment by soimkim** [comment]
As you said, it's better to delete "build" from the "build log".

**Comment by riyenas0925** [comment]
@soimkim 
I modified it as you said.
The final workflow is shown below.

![스크린샷 2021-08-12 오후 8 31 08](https://user-images.githubusercontent.com/32615702/129189722-03ed93b0-35cc-485b-8ebe-769a309822a1.png)

**Comment by soimkim** [comment]
Awesome.
