### ISSUE TITLE
Show OSS list over 10 items in bulk registration page

### ISSUE THREAD

**Issue by syleeeee** [fosslight/fosslight#495]
**Describe the bug**
The bulk registration page doesn't show the whole items over 10.

**To Reproduce**
Steps to reproduce the behavior: Upload an excel sheet with over 10 items in it on the bulk registration.

**Expected behavior**
I think it should show all the items and mark the page number.

**Screenshots**
The Excel sheet: 
![image](https://user-images.githubusercontent.com/6274210/166432984-5a14add7-2d2f-4b81-9648-94e4fc22a05c.png)

The bulk registration page:
![image](https://user-images.githubusercontent.com/6274210/166433088-0445c6fa-b985-4e4f-b0d7-b3d5682fbe85.png)

**System Environment (please complete the following information):**
 - Browser [Chrome]
 - Version [100.0.4896.127]
 - Etc

**Additional context**

**Comment by soimkim** [comment]
This bug fix was released in v1.3.6.
