### ISSUE TITLE
Move the Drop button to the right of the Delete button in "Project > Basic Information"

### ISSUE THREAD

**Issue by suhwan-cheon** [fosslight/fosslight#52]
## Description

- Move the Drop button to the right of the Delete button in "Project > Basic Information"

### Screenshot
![image](https://user-images.githubusercontent.com/52690419/129199676-75dd561e-4b63-4a4d-93ea-779795410637.png)

## Type of change
Please insert 'x' one of the type of change.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [x] Refactoring, Maintenance
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

**Comment by riyenas0925** [comment]
@suhwan-cheon 

The .DS_Store files and Basic files seem to be personal files. Can you please remove these two files? 👍

**Comment by suhwan-cheon** [comment]
Oh right. I will delete it!
Thanks!

**Comment by soimkim** [comment]
It was a nice code review and a nice PR. 👍
