### ISSUE TITLE
Self-check > Change the column name to CVSS Score to Vulnerability.

### ISSUE THREAD

**Issue by soimkim** [fosslight/fosslight#534]
Self-check > Change the column name from "CVSS Score" to "Vulnerability".
![image](https://user-images.githubusercontent.com/4284712/171609103-57e341de-d93c-4449-939b-7f6dd9686969.png)

**Comment by MyunghyunNero** [comment]
i want to take this task,can i try it? 😊

**Comment by soimkim** [comment]
@MyunghyunNero, I look forward to your contribution. 😃
