### ISSUE TITLE
Self-check > Change tab name from "oss List" to "OSS List"

### ISSUE THREAD

**Issue by soimkim** [fosslight/fosslight#535]
Self-check > Change tab name from "oss List" to "OSS List"
![image](https://user-images.githubusercontent.com/4284712/171609605-807a9556-6cdf-4b1b-960c-70fe65e16f79.png)

**Comment by Gseungmin** [comment]
i want to take this task 😄

**Comment by soimkim** [comment]
@Gseungmin , I look forward to your contribution. 😃
