### ISSUE TITLE
Add auto-updating CHANGELOG.md on develop branch

### ISSUE THREAD

**Issue by riyenas0925** [fosslight/fosslight#57]
**Is your feature request related to a problem? Please describe.**
* Add auto-updating CHANGELOG.md on develop branch

**Describe the solution you'd like**
* Currently, only apply automatically to the main branch
* Using the matrix function of Github actions, both develop and main branches will be applied automatically.

**Comment by riyenas0925** [comment]
@soimkim 
There are no conflicts, but I checked that the commits were duplicated.
I'll think of a new way to PR again. Thanks for the feedback 😄 

![스크린샷 2021-08-13 오후 5 48 13](https://user-images.githubusercontent.com/32615702/129331132-23290d29-db93-40c4-908a-6a3dedd42ea0.png)

**Comment by riyenas0925** [comment]
@soimkim 
I've been thinking about various ways, but how about doing it in the following way?

In Merge PR, /changelog is commented, creating a new changelog and committing it to the development branch. When this branch merge to the main, the changed changelog will automatically exist in the main and development.

Below is an example similar to the way I thought.
![51547853-14a57b00-1e35-11e9-841d-33114f0f0bd5](https://user-images.githubusercontent.com/32615702/129341355-bd40e406-9e92-48f6-beb4-c1f866a88b1d.gif)

**Comment by riyenas0925** [comment]
@soimkim 
I've tried a number of ways, but I'm having problems for the following reasons:

### case 1
advantages : There is no duplicated of commit
disadvantages : Main Branch is a previous release of changelog

To prevent duplicate commits, if you create a changelog in the develop branch and merge it into the main branch, both branches have the same changelog. However, since the changelog is created after the release has been published, this method ensures that the develop branch has the latest changelog, but the main branch has the changelog of the previous release.
![스크린샷 2021-08-14 오전 12 16 29](https://user-images.githubusercontent.com/32615702/129381041-83af1ea1-0fda-4864-974c-4fffd2cc7d74.png)

### case 2
advantages : All branches are the latest release of changelog.
disadvantages : Duplicate occurrence of commitment

If you commit the change log in both develop and master branches, it will work as follows, but the same commit will be duplicated when merged into main later.
![스크린샷 2021-08-14 오전 12 00 04](https://user-images.githubusercontent.com/32615702/129376926-74381f58-6ca3-4f88-80ab-64cc24663b62.png)

### case 3
This is a method of adding the changelog to the develop branch before merging in PR and then proceeding with the merge. But it failed because it was before release.

### conclusion
I think it would be difficult to change the changelog without committing in the develop branch because all the methods are released in the main branch. Therefore, In the second case, if duplicate commits are displayed separately into Update Changelog on develop branch and Update Changelog on main branch, wouldn't duplication be avoided?

![스크린샷 2021-08-14 오전 12 22 56](https://user-images.githubusercontent.com/32615702/129381858-dd6a349a-a874-4405-a256-988a9fe8447b.png)

I'd like to hear from the maintainer Thank you!

**Comment by soimkim** [comment]
Are you saying that each commit in case 2 is left with a different commit message so it's not a duplicate commit?
That seems like the best way. 👍

**Comment by riyenas0925** [comment]
@soimkim 
Thank you for your comments!
