### ISSUE TITLE
Change the multilingual setting to ignore the country

### ISSUE THREAD

**Issue by soimkim** [fosslight/fosslight#575]
**Describe the bug**
If the system language is set to English and the region is Korea, an error occurs.
![image](https://user-images.githubusercontent.com/4284712/179394453-4a56bd09-695c-4c6d-a168-a5b3739f646e.png)

Error message when accessing the login screen with 127.0.0.1:8180/
`java.util.MissingResourceException: Can't find bundle for base name messages/message, locale en_KR
`

**Expected behavior**
Modify the multilingual setting to load only the language without looking at the country code.

**Comment by yujung7768903** [comment]
@soimkim Can I take this issue?
