### ISSUE TITLE
Uncaught TypeError when checking license details

### ISSUE THREAD

**Issue by ubermen5che** [fosslight/fosslight#59]
**Describe the bug**

`The 'Uncaught TypeError:Cannot read property 'replace' of undefined` error on the license details page is caused by an invalid conditional expression in code located at `/src/main/webapp/WEB-INF/views/admin/license/view-js.jsp` It occurs due to If `data.detail.restriction` does not exist, `undefined` type is entered as a conditional expression. Therefore, in the current conditional expression, `undefined` is not `''`, so the condition is true and the replace property that the `undefined` type does not have is accessed and an error occurs.

```jsx
if(data.detail.restriction != ''){
	$('#restriction').append(data.detail.restriction.replace(/,/gi, ", "));
}
```

**To Reproduce**

(User) → License List → License Search → Click License → License Details Page
**(It occurs only when there is no restriction information such as Academic Free License v1.2, Apache License 1.1.)**

**Screenshots**
 
![스크린샷_13-08-2021_19 28 28](https://user-images.githubusercontent.com/76172759/129361679-8858fbc5-4c4f-4db0-aa65-a6b2f993f32f.png)

**System Environment**

- Browser : Chrome
- Version : 92.0.4515.131

**Additional context**
I suggest the following code modifications:

```jsx
if(data.detail.restriction){
	$('#restriction').append(data.detail.restriction.replace(/,/gi, ", "));
}
```

If we use a conditional expression like the code above, it returns false successfully when `restriction` is `undefined` or `''`. So we avoid calling the `replace` property when `restriction` is `undefined` or `''` and avoid Uncaught TypeError.

**Comment by soimkim** [comment]
@ubermen5che , I'm waiting for your contribution.
