### ISSUE TITLE
/api/v1/vulnerability_data > Enter at least one of CVE-ID or OSS Name.

### ISSUE THREAD

**Issue by soimkim** [fosslight/fosslight#627]
**Describe the bug**
http://demo.fosslight.org/swagger-ui.html
/api/v1/vulnerability_data 
- It is not possible to search by CVE-ID alone. That is, it is OK even if only one of CVE-ID or OSS Name is input, but it does not work if OSS Name is not input.

**Expected behavior**
/api/v1/vulnerability_data 
- Please make it searchable even if only one of CVE-ID or OSS Name is entered.
- If both are not entered, return an error.

**Comment by MiniVee** [comment]
@soimkim Can I take this issue??? I'll do it perfectly.😀
