### ISSUE TITLE
It is required to show detailed messages when OSS bulk request

### ISSUE THREAD

**Issue by FRESH-TUNA** [fosslight/fosslight#665]
## AS-IS
![스크린샷 2022-09-13 오후 3 24 04](https://user-images.githubusercontent.com/33149791/189827189-770f506f-836c-43d8-b5c2-afb01168a6da.png)

After OSS bulk request, There is no way to know failure reason. (just show failed or success)
And there is no warning messages. So users can't know result is successful or not **until sending a request**.

## TO-BE
- Add detail failure message (duplicated, required missing, unconfirmed license ...)
- Add warning messages like project identification

**Comment by soimkim** [comment]
완료!
