### ISSUE TITLE
Add license information display when clicking the Restriction icon

### ISSUE THREAD

**Issue by riyenas0925** [fosslight/fosslight#70]
**Is your feature request related to a problem? Please describe.**
Add license information display when clicking the Restriction icon

**Describe the solution you'd like**
Click the Restriction icon to pop up the license information.
![스크린샷 2021-08-18 오후 8 00 57](https://user-images.githubusercontent.com/32615702/129887234-b387e653-22a4-43c8-805f-b314165d50f8.png)

The picture below shows the license information when you click the license icon.
![스크린샷 2021-08-18 오후 8 02 57](https://user-images.githubusercontent.com/32615702/129887333-5bc2f36d-8511-4bd7-a369-08f9140cda83.png)

**Comment by riyenas0925** [comment]
@soimkim 
implemented it as below.

The description says double-click, but does this mean that it needs to be double-clicked to open? Or does it open just by pressing it once like the gif below? 

I'd like to hear the maintainer's opinion!

![Aug-18-2021 20-58-22](https://user-images.githubusercontent.com/32615702/129894356-4e04fa77-56da-4bff-bda5-03bcda8ae5b2.gif)

**Comment by soimkim** [comment]
@riyenas0925 ,
When double-clicking, I wanted to check the detailed information of the license.
However, looking at the screen you attached, icons like License detail display a pop-up when clicked rather than double-clicked.

To be consistent, we need to change the requirement to display a popup when **clicking** the R icon.

**Comment by riyenas0925** [comment]
@soimkim 
Thank you for your opinion. I'll refactor the code and commit it again.

**Comment by riyenas0925** [comment]
@soimkim

Any page that uses the review icon works like this
Please let me know if there is a function that is working incorrectly, thank you!

|page|difference|comment|
|:--:|:--:|:--:|
|OSS Table </br>(Project List -> BOM, Self-Check List, 3rd Party)|![Aug-28-2021 14-40-29](https://user-images.githubusercontent.com/32615702/131207632-1bd4e892-bbc3-4408-949f-f0ad6efc8daa.gif)|hover and license details popup|
|License List|![스크린샷 2021-08-28 오후 2 27 35](https://user-images.githubusercontent.com/32615702/131207373-9b6d39b9-041f-414d-9911-7be6c3c6a681.png)|only hover|
|License Details popup|![스크린샷 2021-08-28 오후 2 10 03](https://user-images.githubusercontent.com/32615702/131207048-4ca8ba8a-88f6-4f60-b366-37826199085d.png)|only hover|
|Project List|![스크린샷 2021-08-28 오후 2 18 30](https://user-images.githubusercontent.com/32615702/131207187-7b3f2737-97ba-499c-bffb-c33bc4a2ee1b.png)|Same review icon but no hover|

**Comment by riyenas0925** [comment]
@soimkim 
I reflected what we discussed. Please review the code
