### ISSUE TITLE
Two open source package repositories (Pub, CocoaPods) are missing from the source code

### ISSUE THREAD

**Issue by namkyu1999** [fosslight/fosslight#78]
**Describe the bug**
FOSSLight uses 6 open source package repositories (GitHub, Maven, PyPI, npm, Pub, CocoaPods) to check various information of open source. However, only 4 open source package repositories are specified in fosslight_create.sql, OssServiceImpl::checkOssName function, and OssServiceImpl::saveOssCheckName function.

- db/initdb.d/fosslight_create.sql
![image](https://user-images.githubusercontent.com/53862866/130304695-89ca33c5-1231-4a8e-a6b3-92036d320f18.png)

- OssServiceImpl::checkOssName
https://github.com/fosslight/fosslight/blob/a5ed084d4a3726550d1474822af5914e7af4bc90/src/main/java/oss/fosslight/service/impl/OssServiceImpl.java#L1602

```
 switch(urlSearchSeq) {
    case 0: // github
        p = Pattern.compile("((http|https)://github.com/([^/]+)/([^/]+))");
		break;
	case 1: // npm
	    p = Pattern.compile("((http|https)://www.npmjs.com/package/([^/]+))");
		break;
	case 2: // pypi
	    p = Pattern.compile("((http|https)://pypi.org/project/([^/]+))");
		break;
	case 3: // maven
	    p = Pattern.compile("((http|https)://mvnrepository.com/artifact/([^/]+)/([^/]+))");
		break;
	default:
	    break;
}
```

- OssServiceImpl::saveOssCheckName
https://github.com/fosslight/fosslight/blob/a5ed084d4a3726550d1474822af5914e7af4bc90/src/main/java/oss/fosslight/service/impl/OssServiceImpl.java#L1758
```
switch(urlSearchSeq) {
    case 0: // github
        p = Pattern.compile("((http|https)://github.com/([^/]+)/([^/]+))");
		break;
	case 1: // npm
	    p = Pattern.compile("((http|https)://www.npmjs.com/package/([^/]+))");
		break;
	case 2: // pypi
	    p = Pattern.compile("((http|https)://pypi.org/project/([^/]+))");
		break;
	case 3: // maven
	    p = Pattern.compile("((http|https)://mvnrepository.com/artifact/([^/]+)/([^/]+))");
		break;
	default:
	    break;
}
```

**To Reproduce**
Added 2 open source package repository information (Pub, CocoaPods) to the source code.

**Comment by soimkim** [comment]
@namkyu1999 ,
What links are you going to add for Pub, CocoaPods?

**Comment by namkyu1999** [comment]
Pub return links like 'https://pub.dev/packages/[package_name]' (ex. https://pub.dev/packages/animated_appbar)
and CocoaPods return links like 'https://cocoapods.org/pods/[package_name]' (ex. https://cocoapods.org/pods/Alert).

**Comment by soimkim** [comment]
Dear @dd-jy (FOSSLight Dependency Maintainer), 
We are going to add a function that automatically changes the OSS Name for the link below (Function to operate when "Check OSS Name" is clicked).
ex)
- 'https://pub.dev/packages/[package_name]'  -> pub:[package_name]
- 'https://cocoapods.org/pods/[package_name]'  -> cocoapods:[package_name]

Do you have any opinions on this?

**Comment by dd-jy** [comment]
@soimkim, @namkyu1999,
It's good to me.😃
