### ISSUE TITLE
Recommend the OSS Name according to the OSS Naming Rule

### ISSUE THREAD

**Issue by namkyu1999** [fosslight/fosslight#79]
**Is your feature request related to a problem? Please describe.**
When pressed button like below(in Project List > SRC tab) ,
![image](https://user-images.githubusercontent.com/53862866/130305524-13d01de1-af33-4cbb-ba1e-1908db875485.png)
FOSSLight recommends an oss name by checking the oss list.
If the download location is not stored in the OSS List only for the OSS Name that is an Unconfirmed Open Source Warning message, recommend the OSS Name according to the OSS Naming Rule.

**Describe the solution you'd like**
- OSS Naming Rule : 
— GitHub link: (owner)-(repository)
ex) https://github.com/fosslight/fosslight ⇒ fosslight-fosslight
— pypi link :  pypi:(module_name)
— npm link : npm:(module_name)
- maven link : (group_id):(artifact_id)
— pub link : pub:(module_name)
- pods link : cocoapods:(module_name)

**Comment by soimkim** [comment]
Dear @namkyu1999 ,
Does this function work when the **"Check OSS Name"** button is clicked?

**Comment by namkyu1999** [comment]
Yes. I will fix it in more detail

**Comment by namkyu1999** [comment]
Dear @soimkim ,
Issue #78 is an issue that must be resolved prior to completing issue #79. So, is it okay to make two issues into separate commits and request them as one pull request?

**Comment by soimkim** [comment]
@namkyu1999 ,
The two issues are related, so let's make separate commits into one PR. 😃
