### ISSUE TITLE
Add label:improvement to also appear as child of Feature in release draft

### ISSUE THREAD

**Issue by riyenas0925** [fosslight/fosslight#80]
**Is your feature request related to a problem? Please describe.**
Add label:improvement to also appear as child of Feature in release draft

**Describe the solution you'd like**
Edit release-drafter-config.yml so that label:improvement and label:enhancement are under feature.

**Comment by riyenas0925** [comment]
@soimkim 
All other labels are lowercase, but we have confirmed that only label:Improvement starts with uppercase letters. Could you change this to a lower case?

Or should I add it to release-drafter-config as it is? I'd appreciate your opinion!

**Comment by soimkim** [comment]
OK. I will change it.

**Comment by riyenas0925** [comment]
@soimkim 
Thank you for your comments! 
I will work with lowercase label:improvement and post the PR

**Comment by soimkim** [comment]
![image](https://user-images.githubusercontent.com/4284712/130308422-78b8cb52-ce57-4108-95a2-df3e0d7f2df2.png)
