### ISSUE TITLE
OSS > Delete WITH from the detected license field. (WITH is legacy.)

### ISSUE THREAD

**Issue by soimkim** [fosslight/fosslight#808]
**Describe the solution you'd like**
OSS List > Add > Delete WITH from the Detected license field.
(WITH is legacy.)
![image](https://user-images.githubusercontent.com/4284712/216217140-063ddbc1-81d5-4335-8c99-b9a5070e8dd6.png)

**Comment by dener8** [comment]
Hi. Can I contribute to this issue? 
It seems that the term "Detected license" is mistakenly written as "Declared license" in this text.
If you give me a chance, I will contribute. Thank you.

**Comment by d-h-k** [comment]
I've just put up a PullRequest for this issue.  https://github.com/fosslight/fosslight/pull/867
