### ISSUE TITLE
3rd Party List > Expand > Add Description search

### ISSUE THREAD

**Issue by soimkim** [fosslight/fosslight#816]
3rd Party List > Expand > Add `Description `search.
![image](https://user-images.githubusercontent.com/4284712/218899648-ac82c673-00e2-4495-9ef1-774918822ae6.png)
![image](https://user-images.githubusercontent.com/4284712/218899673-b418eb35-4f11-4b41-b6b1-6173a0767446.png)

**Comment by cookienc** [comment]
@soimkim I want to try this issue. May I try this one?

**Comment by soimkim** [comment]
@cookienc , I look forward to your contribution. 🤗
