### ISSUE TITLE
Project List, 3rd Party List > Add watcher search

### ISSUE THREAD

**Issue by soimkim** [fosslight/fosslight#817]
Project List, 3rd Party List > Add `watcher `search
![image](https://user-images.githubusercontent.com/4284712/218900162-9b652c07-ce09-4dfe-ab9f-06ed7f06af14.png)

**Comment by Youngseo-Jeon0313** [comment]
Please I'd love to work on this issue. Thank you.

**Comment by soimkim** [comment]
@Youngseo-Jeon0313 , I look forward to your contributions. :smiley:

**Comment by Youngseo-Jeon0313** [comment]
@soimkim Hello, I have a question while implementing this issue! When I press the Search button for search on the Project List and 3rd Party List pages, columns related to watcher are not generated below, so I wonder **if I need to implement table creation and DB connection related to Watcher!**

**Comment by Youngseo-Jeon0313** [comment]
@soimkim Hello, I have a question while implementing this issue! When I press the Search button for search on the Project List and 3rd Party List pages, columns related to watcher are not generated below, so I wonder **if I need to implement table creation and DB connection related to Watcher!**
