### ISSUE TITLE
Change the default value of the search in Statistics

### ISSUE THREAD

**Issue by dener8** [fosslight/fosslight#860]
**Is your feature request related to a problem? Please describe.**
The last day of the search date is set as the last day of the year, so unnecessary searches are performed when the page is loaded.
<img width="1056" alt="image" src="https://github.com/fosslight/fosslight/assets/84485400/35af4136-324a-4776-9894-03cb5e18f426">

**Describe the solution you'd like**
I think it would be good to set the period of search date to the last 365 days.
For example, if today is June 18, 2023, then the default value for search date is June 19, 2022 to June 18, 2023.

**Describe alternatives you've considered**
I think it would be good to change the default value of the last day of the search date to today.

**Comment by dener8** [comment]
I'm sorry, but I pressed the "unassign me" button by mistake.

**Comment by k2heart** [comment]
So sorry for the late response. 
The default setting is because most companies require these statistics on a yearly basis.

**Comment by dener8** [comment]
Thank you for your response. It's good that I know something new!
Then should I close this issue?
