### ISSUE TITLE
(Improvement) REST API > /api/v1/create_project > additional information

### ISSUE THREAD

**Issue by soimkim** [fosslight/fosslight#874]
ko. /api/v1/create_project 에 additional information 입력 Parameter를 추가합니다. (필수 입력값 아님)

eng. Add additional information input parameter to /api/v1/create_project. (not required input)

![image](https://github.com/fosslight/fosslight/assets/4284712/10dfc2cd-60c2-4337-94fb-67dcaf407ac1)

Ref. https://fosslight.org/fosslight-guide-en/features/2_rest_api.html

**Comment by moto3z** [comment]
I would like to try to improve on this issue

**Comment by jongwooo** [comment]
@moto3z Sure, feel free to take it.

**Comment by moto3z** [comment]
@jongwooo  😀 thank you !

**Comment by moto3z** [comment]
# title

<br><hr><br>

## 1) Conclusion: The function seems to work well currently
- in my localhost screenshot, courrent develop revision (commit id = 5923e6ddd594063e7e95889daf30cdf9412efaab )
<img width="1531" alt="image" src="https://github.com/fosslight/fosslight/assets/31065684/c37cf961-0d29-4a76-afbf-384b3b323baf">

<br><hr><br>

## 2) Code that actually works this function 

- in my opinion 'ProjectController.java'  is actually work this function (that registe about 'additional infomation' )
```
@PostMapping(value = PROJECT.SAVE_AJAX)
	public @ResponseBody ResponseEntity<Object> saveAjax(@ModelAttribute Project project, HttpServletRequest req,
			HttpServletResponse res, Model model) {
```

###  mentioned on issue '/api/v1/create_project' I don't know how this has to do with the issue. can you give me some help?

<br><hr><br>

## 3)

**Comment by soimkim** [comment]
@moto3z , Comment와 additional information은 다른 값입니다.

**Comment by soimkim** [comment]
본 이슈관련 버그가 발견되어 함께 수정하고자, 제가 F/U할께요~ 😃
