### ISSUE TITLE
(Improvement) Project List > BOM Compare 

### ISSUE THREAD

**Issue by soimkim** [fosslight/fosslight#875]
**Project List > BOM Compare** 

Check two projects in the project list and click BOM Compare
     1. AS-IS: With two project ids entered, you need to press the search button again to see the BOM Compare result.
     2. TO-BE: When two project ids are entered and the Search button is clicked, the BOM Compare tab appears.

Project list에서 project 두개 체크 후 BOM Compare 클릭시 
    1. AS-IS : 두개의 project id가 입력된 채로, 다시 search 버튼을 눌러야 BOM Compare결과를 볼 수 있음
    2. TO-BE:  두개의 project id가 입력되고 Search 버튼까지 클릭된 상태로 BOM Compare 탭이 뜨도록 함

**Comment by dener8** [comment]
Can I try this issue? 😃

**Comment by 70825** [comment]
@dener8 Sure~
