### ISSUE TITLE
(New feature) Project > Packaging >  File extension not supported

### ISSUE THREAD

**Issue by soimkim** [fosslight/fosslight#881]
(ENG) Show a pop-up message when an unsupported file extension is uploaded in the Packaging tab.
- Supported file extensions: System > Code Management > Code No: 120 > Code Detail: 16
ex. In the pop-up message below, tar.gz,gz,zip are values loaded from Code Management.

(KO) Packaging 탭에 지원하지 않는 파일 확장자가 업로드되면 팝업 메세지를 띄워라.
- 지원되는 파일 확장자 : System > Code Management > Code No : 120 > Code Detail : 16
ex. 하기 팝업 문구에서 tar.gz,gz,zip는 Code Management에서 load한 값

![image](https://github.com/fosslight/fosslight/assets/4284712/332c7af6-6965-4d3a-8262-17dc5f830355)

Pop-up message : 
- KO : 
```
지원하지 않는 파일 확장자를 업로드했다.
- 지원하는 파일 확장자 : tar.gz,gz,zip
```
- ENG : 
```
You uploaded an unsupported file extension.
- Supported file extensions: tar.gz,gz,zip
```

**Comment by MyunghyunNero** [comment]
can I try it?😀
