### ISSUE TITLE
(New Feature) OSS > add > Show new icon for newly added nicknames 

### ISSUE THREAD

**Issue by soimkim** [fosslight/fosslight#882]
eng. 
- Newly added nicknames are displayed with a new icon in front.

ko. 
- 신규로 추가된 nickname은 앞에 new 아이콘을 표시

![image](https://github.com/fosslight/fosslight/assets/4284712/90ba8f72-b40c-41dc-8683-7df3cd2f6bc4)

**Comment by Lightieey** [comment]
Can I try this?

**Comment by jongwooo** [comment]
@Lightieey Sure, feel free to take it.
