### ISSUE TITLE
Save License Controller Refacotring 

### ISSUE THREAD

**Issue by Gseungmin** [fosslight/fosslight#886]
**Is your feature request related to a problem? Please describe.**

I found out duplicated codes for storing license

Maybe I made a mistake when I implemented it. 

can I refactor this codes?

**Describe the solution you'd like**
Now we can find out duplicated codes for storing license in License saveAjax Controller and LicenseService

I'm gonna integrate the codes and manage them in LicenseService

I checked that These two codes match perfectly

```Java
public Map<String, Object> saveLicense(LicenseMaster licenseMaster) {}

public @ResponseBody ResponseEntity<Object> saveAjax(
			@ModelAttribute LicenseMaster licenseMaster
			, HttpServletRequest req
			, HttpServletResponse res
			, Model model){}
```

**Comment by 70825** [comment]
https://github.com/fosslight/fosslight/pull/887
