### ISSUE TITLE
OSS List > View all OSS list in initial screen

### ISSUE THREAD

**Issue by jiwon83** [fosslight/fosslight#890]
If I select OSS List on the left side tab, I can't see anything in the initial screens.
So I have to click the search button to show all OSS lists.

 I think that it's better to show all OSS lists on the initial screen. Would it be okay?

AS-IS :
![before](https://github.com/jiwon83/SpringBoot_Basic/assets/88698607/b2661860-ace6-416d-8683-66047420549a)

TO-BE: 
![image](https://github.com/jiwon83/SpringBoot_Basic/assets/88698607/1f7570d8-0b2b-4c68-ab6f-3fd5c6a69af8)
there are all OSS lists.

**Comment by soimkim** [comment]
@jiwon83 ,
If there is too much OSS information, there is an issue that the loading speed takes a long time when entering the OSS List.
For this reason, it was deliberately not searched immediately.
