### ISSUE TITLE
[New REST API] /api/v1/prj_not_applicable

### ISSUE THREAD

**Issue by dd-jy** [fosslight/fosslight#906]
/api/v1/prj_not_applicable
(ko) 

- input : 
    1. Tab : 3rd, SRC, BIN 중 하나의 값 (필수 입력)
    2. Project ID (필수 입력)
- Project Identification단계 해당 탭의 'Not applicable'을 체크 후 save한 상태로 변경되도록 한다.
    -  해당 Project의 Identification 탭내 Save 버튼이 활성화되지 않은 경우 (ex. Identification이 confirm인 상태 OR Project가 Drop 또는 Complete된 상태) error를 return. (Identification이 progress 상태인 경우만 저장 가능하도록 함.)
    - 해당 Project에 쓰기 권한이 없는 경우 (Watcher, creator, admin, reviewer가 아닌 경우) error를 return

(eng)
The value of one of 3rd, SRC, and BIN is required input. and the "Not applicable" of the corresponding tab of the Project Identification step is checked and changed to a saved state.

**Comment by moto3z** [comment]
can i try this issue?
