### ISSUE TITLE
When packaging confirm, combine comments into one

### ISSUE THREAD

**Issue by soimkim** [fosslight/fosslight#907]
When packaging confirm, combine comments into one.

Eng.
When you click Confirm in the Packaging step
- AS-IS: Separate comments are left for each attached file.
- TO-BE: Output all in "Packaging > Confirmed" with one comment.

Ko.
Packaging 단계에서 Confirm 클릭시 
- AS-IS : 첨부된 파일별로 Comment가 따로 남겨짐.
- TO-BE: Packaging > Confirmed 커맨트에 하나의 커맨트로 합쳐서 출력

![image](https://github.com/fosslight/fosslight/assets/4284712/2cf6d4e8-a307-44fc-8665-44217c851835)

**Comment by MyunghyunNero** [comment]
can I try it?😃

**Comment by jongwooo** [comment]
@MyunghyunNero Sure:)
