### ISSUE TITLE
Announce pop-ups added from System > Notification

### ISSUE THREAD

**Issue by parkmuhyeun** [fosslight/fosslight#918]
1. AS-IS: 로그인 한 후에 뜸
2. TO-BE: 로그인 전 화면에 띄움
    1. 사유 : 로그인하지 않더라도 공지를 확인할 수 있도록 함

**Comment by soimkim** [comment]
본 기능 https://github.com/fosslight/fosslight/commits/bc805ba04028522461492e9af1dfd8ccadf72459에서 반영되어 close합니다.
커뮤니케이션 오류로 인해 번거롭게해드려 죄송합니다. 😢
