### ISSUE TITLE
Use early-return pattern avoids nested conditions

### ISSUE THREAD

**Issue by parkcoldroad** [fosslight/fosslight#919]
## Summary

> An early-return pattern is when a function or method quickly returns a result based on a condition and finishes executing its logic.

I found nested conditions in [/api/v1/ApiSelfCheckController/](https://github.com/fosslight/fosslight/blob/212cca8a80de4957378193dd88b18b98430487eb/src/main/java/oss/fosslight/api/controller/v1/ApiSelfCheckController.java#L135-L225)
Nested conditions can cause poor readability, maintenance difficulties, difficulty understanding logic flow, and testing difficulties.
I think early-return can solve these problems.

**AS-IS**
```java
  if (searchFlag) {
    if (ossReport != null) {
        // ...
    } else {
        return responseService.getFailResult(CoConstDef.CD_OPEN_API_PARAMETER_ERROR_MESSAGE
                , CoCodeManager.getCodeString(CoConstDef.CD_OPEN_API_MESSAGE, CoConstDef.CD_OPEN_API_PARAMETER_ERROR_MESSAGE));
    }
} else {
    return responseService.getFailResult(CoConstDef.CD_OPEN_API_PERMISSION_ERROR_MESSAGE
            , CoCodeManager.getCodeString(CoConstDef.CD_OPEN_API_MESSAGE, CoConstDef.CD_OPEN_API_PERMISSION_ERROR_MESSAGE));
}
```

**TO-BE**
```java
 if (!searchFlag) {
    return responseService.getFailResult(CoConstDef.CD_OPEN_API_PERMISSION_ERROR_MESSAGE
            , CoCodeManager.getCodeString(CoConstDef.CD_OPEN_API_MESSAGE, CoConstDef.CD_OPEN_API_PERMISSION_ERROR_MESSAGE));
}

if (ossReport == null) {
    return responseService.getFailResult(CoConstDef.CD_OPEN_API_PARAMETER_ERROR_MESSAGE
            , CoCodeManager.getCodeString(CoConstDef.CD_OPEN_API_MESSAGE, CoConstDef.CD_OPEN_API_PARAMETER_ERROR_MESSAGE));
}
    // ...

```

## References
https://medium.com/swlh/return-early-pattern-3d18a41bba8

**Comment by jongwooo** [comment]
@parkcoldroad Good Point! Could you send a PR for this?
