### ISSUE TITLE
Update default configuration setting Refactoring

### ISSUE THREAD

**Issue by hseungho** [fosslight/fosslight#923]
**Is your feature request related to a problem? Please describe.**

I found duplicate code for the logic for SecurityContext in the ConfigurationServiceImpl class. 

I looked at the other service classes and saw that they inherit from the CoTopComponet class and get their SecurityContext through that class.

Can I refactor this codes?

**Describe alternatives you've considered**
AS-IS:  
The ConfigurationServiceImpl class does not inherit from CoTopComponent and is getting the SecurityContext from inside the method. 

TO-BE:  
Change the ConfigurationServiceImpl class to inherit from CoTopComponent and call the loginUserName method of the parent class.

**Comment by jongwooo** [comment]
@hseungho Could you send a PR for this?

**Comment by hseungho** [comment]
Of Course! Thank you!
