### ISSUE TITLE
Refactoring for deprecated Slack code

### ISSUE THREAD

**Issue by che-so** [fosslight/fosslight#926]
I found deprecated code in /github/workflows/release-publish.yml.

We've been informed that we're not using Slack this year. We decided it would be more efficient for the program to remove unused features.

Can I refactor this codes?

**AS-IS:**
Slack Workflow Notification feature still exists in program code even though it's disabled

**TO-BE:**
Remove unused Slack Workflow Notification features

**Comment by 70825** [comment]
Good Point 👍

**Comment by jongwooo** [comment]
@che-so #713 might be helpful.
