### ISSUE TITLE
OSS List > search with vulnerability

### ISSUE THREAD

**Issue by dd-jy** [fosslight/fosslight#939]
OSS List 내 검색 창 조건에서 vulnerability 추가

- 검색 조건 명 : Vulnerability (>=)
- input : 숫자
- 입력된 input 값보다 vulnerability score가 높은 경우 검색

Adding vulnerability in the search window in the OSS List menu.

- Search condition name: Vulnerability (>=)
- input : number
- Search if the vulnerability score is higher than the input value entered

**Comment by jiwon83** [comment]
Can I work on this?

**Comment by 70825** [comment]
Sure~

**Comment by soimkim** [comment]
Related bugs are addressed at https://github.com/fosslight/fosslight/issues/992.
