### ISSUE TITLE
Modify pop-up phrases that occur when you press the reopen button

### ISSUE THREAD

**Issue by suhwan-cheon** [fosslight/fosslight#94]
## Description

- Modify pop-up phrases that occur when you press the reopen button in Project > Basic Information
- Creator Date : -> Created Date
- delete this phrase "Are you sure you want to reject?"

### Screenshot
![image](https://user-images.githubusercontent.com/52690419/131064854-ac6d2b86-08de-4fd6-bcc0-cafb792ee309.png)

## Type of change
Please insert 'x' one of the type of change.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [x] Refactoring, Maintenance
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

**Comment by soimkim** [comment]
I close this issue because it has been merged.
