### ISSUE TITLE
 Extended Check OSS Name function

### ISSUE THREAD

**Issue by MyunghyunNero** [fosslight/fosslight#964]
**Is your feature request related to a problem? Please describe.**
1. Extended Check OSS Name function
    - Check OSS Name is a button that exists in Project > Identification, 3rd Party, Self-check, and automatically creates a recommended OSS name according to the link.
    - Format to be added: [https://stackoverflow.com/revisions/{ID}/](https://stackoverflow.com/revisions/29867106/2) → stackoverflow-{ID}
    ex.
    https://stackoverflow.com/revisions/29867106/2 → stackoverflow-29867106

**Comment by MyunghyunNero** [comment]
@dener8

**Comment by dener8** [comment]
May I try this issue? 🌝

**Comment by jongwooo** [comment]
@dener8 Sure, feel free to take it.
