### ISSUE TITLE
Change Docker Image Build Method from Dockerfile to Jib

### ISSUE THREAD

**Issue by Gseungmin** [fosslight/fosslight#973]
**Is your feature request related to a problem? Please describe.**
* Currently, Docker images are being built using Dockerfile, but it takes a considerable amount of time for the build process. Although we utilize the Docker buildx and QEMU method, the use of the Docker daemon leads to additional time consumption. The Docker daemon is a process that runs in the background, managing Docker's build and execution. The overhead generated in this process results in an extended build time.

**Describe the solution you'd like**
* By using Jib, a Java image build tool provided by Google, the image build time can be significantly reduced. Jib does not rely on the traditional Docker daemon approach, thus enhancing the efficiency of the build process.

**Comment by jongwooo** [comment]
@Gseungmin I think it's a nice try, but could Jib replace all the existing features like multi-platform builds?

**Comment by Gseungmin** [comment]
> @Gseungmin I think it's a nice try, but could Jib replace all the existing features like multi-platform builds?

While Jib can be used for building Java-based images, for services like the fosslight scanner that are Python-based, it seems we still need to use Dockerfile.

**Comment by jongwooo** [comment]
@Gseungmin Note that `platform` I'm referring to is the platform the Docker image will run on. In fosslight, a multi-platform build is done as follows:

https://github.com/fosslight/fosslight/blob/d129c17cccb2f779651344bfcd81f224eac9ff56/.github/workflows/release-publish.yml#L123-L128
