### ISSUE TITLE
OSS List > Vulnerability Search > Rows that do not meet vulnerability search conditions

### ISSUE THREAD

**Issue by soimkim** [fosslight/fosslight#992]
**AS-IS:** 
![image](https://github.com/fosslight/fosslight/assets/4284712/e1990e45-4a54-4fe8-a2d4-1c59b1c31298)
Versions that are not included in the vulnerability search conditions in the OSS List are also searched in the list.

**TO-BE:**
Rows that do not meet the vulnerability search conditions in the OSS List should not be included in the search results.

**Comment by Youngseo-Jeon0313** [comment]
Can I try this ??

**Comment by 70825** [comment]
Sure~
